### ISSUE TITLE
Make sure the containers comply with the manylinux2014 needs

### ISSUE THREAD

**Issue by dpinte** [enthought/edm-containers#17]
See https://www.python.org/dev/peps/pep-0599/

For example: RPM-based systems should have the following packages installed to ensure the appropriate list of libraries are available:

Package | Libraries
-- | --
glib2 | libglib-2.0.so.0, libgthread-2.0.so.0, libgobject-2.0.so.0
glibc | libresolv.so.2, libutil.so.1, libnsl.so.1, librt.so.1, libpthread.so.0, libdl.so.2, libm.so.6, libc.so.6
libICE | libICE.so.6
libX11 | libX11.so.6
libXext: | libXext.so.6
libXrender | libXrender.so.1
libgcc: | libgcc_s.so.1
libstdc++ | libstdc++.so.6
mesa | libGL.so.1

For Debian based systems:

Package | Libraries
-- | --
libc6 | libdl.so.2, libresolv.so.2, librt.so.1, libc.so.6, libpthread.so.0, libm.so.6, libutil.so.1, libnsl.so.1
libgcc1 | libgcc_s.so.1
libgl1 | libGL.so.1
libglib2.0-0 | libgobject-2.0.so.0, libgthread-2.0.so.0, libglib-2.0.so.0
libice6 | libICE.so.6
libsm6 | libSM.so.6
libstdc++6 | libstdc++.so.6
libx11-6 | libX11.so.6
libxext6 | libXext.so.6
libxrender1 | libXrender.so.1

**Comment by ddebeau** [comment]
For CentOS 7, ensuring compliance is as simple as running `yum install glib2 glibc libICE libX11 libXext libXrender libgcc libstdc++ mesa-libGL`. We can likely do something similar with apt.
