### ISSUE TITLE
Reorg & refresh Docker hub

### ISSUE THREAD

**Issue by mplanchard** [enthought/edm-containers#7]
Typical usage for a product, e.g. `postgres` or `python` is to have Docker repos called those things, and then to use tags to separate operating systems, versions, etc.

As such, we should reoganize our Docker repo to be more in line with this standard, i.e. an EDM repo for containers with EDM installed, whose entrypoint is the EDM command, with labels like:

* `latest`
* `latest-centos7`
* `latest-xenial`
* `1.9.2`
* `1.9.2-centos7`
* `1.9.2-xenial`

etc.

The best way to accomplish this will be in conjunction with #6.

**Comment by ZachPope531** [comment]
Closed with #15
